### ISSUE TITLE
Installation documentation broken at different points

### ISSUE THREAD

**Issue by akram** [openshift/csi-driver-shared-resource#58]
While following the installation doc and after the introduction of new resources types, installation breaks at some points:
* using 0.4.8-rc is suffering breaking changes
* daemonset's `hostpath` container image requires `quay.io/openshift/origin-csi-driver-shared-resource:4.10.0` 
* `my-csi-volume`  has a missing `share` attribute

**Comment by gabemontero** [comment]
> While following the installation doc and after the introduction of new resources types, installation breaks at some points:
> 
>     * using 0.4.8-rc is suffering breaking changes
> 
>     * daemonset's `hostpath` container image requires `quay.io/openshift/origin-csi-driver-shared-resource:4.10.0`
> 
>     * `my-csi-volume`  has a missing `share` attribute

`share` attribute is no longer valid @akram 

it is `sharedConfigMap` and `sharedSecret` which map to the new CRDs

**Comment by gabemontero** [comment]
all that doc has been removed and replaced with in playload on tech preview clusters

/close

**Comment by gabemontero** [comment]
weird I do not have authority to close this

@akram can you close this - it is no longer relevant

thanks
